[env]
  TERM = "xterm-256color"

[font]
normal = { family = "CaskaydiaCove Nerd Font", style = "Regular" }
size = 13

[selection]
save_to_clipboard = true

[mouse]
bindings = [
    { mouse = "Right", action = "PasteSelection" },
]

[keyboard]
bindings = [
    { key = "Slash", mods = "Control", chars = "\u001f" },
    { key = "Return", mods = "Alt", action = "None" },
]

