commit:
  disable-body: true
  disable-footer: true
  enable-scope: true
  scopes:
    - bash
    - nvim
  types:
    - text: ✨
      note: "feat: A new feature"
    - text: 🎨
      note: "refactor: A code change that neither fixes a bug nor adds a feature"
    - text: 📝
      note: "docs: Documentation only changes"
    - text: 🔧
      note: "build: Changes that affect the build system or external dependencies (example scopes: gulp, broccoli, npm)"
    - text: 👷
      note: "ci: Changes to our CI configuration files and scripts (examples: CircleCi, SauceLabs)"
  message-template: "{{.Type}} {{if .Scope}}({{.Scope}}): {{end}}{{.Summary}}"
