[fish]
path = "fish"
[fish.target]
linux = "~/.config/fish"

[ghostty]
path = "ghostty"
[ghostty.target]
linux = "~/.config/ghostty"

[go]
path = "go"
[go.target]
linux = "~/.config/go"

[niri]
path = "niri"
[niri.target]
linux = "~/.config/niri"

[nvim]
path = "nvim"
[nvim.target]
linux = "~/.config/nvim"
windows = "~/AppData/Local/nvim"

[sqlite3]
path = "sqlite3"
[sqlite3.target]
linux = "~/.config/sqlite3"
