[alacritty]
path = "alacritty"
[alacritty.target]
linux = "~/.config/alacritty"

[cargo]
path = "cargo"
[cargo.target]
linux = "~/.cargo"

[fish]
path = "fish"
[fish.target]
linux = "~/.config/fish"

[ghostty]
path = "ghostty"
[ghostty.target]
linux = "~/.config/ghostty"

[git]
path = "git"
[git.target]
linux = "~/.config/git"

[go]
path = "go"
[go.target]
linux = "~/.config/go"

[lazygit]
path = "lazygit"
[lazygit.target]
linux = "~/.config/lazygit"

[mpv]
path = "mpv"
[mpv.target]
linux = "~/.config/mpv"

[niri]
path = "niri"
[niri.target]
linux = "~/.config/niri"

[nvim]
path = "nvim"
[nvim.target]
linux = "~/.config/nvim"
windows = "~/AppData/Local/nvim"

[pip]
path = "pip"
[pip.target]
linux = "~/.config/pip"

[sqlite3]
path = "sqlite3"
[sqlite3.target]
linux = "~/.config/sqlite3"

[zellij]
path = "zellij"
[zellij.targets]
linux = "~/.config/zellij"
