[alacritty]
path = "alacritty"
[alacritty.target]
linux = "~/.config/alacritty"
windows = "~/AppData/Roaming/alacritty"

[cargo]
path = "cargo"
[cargo.target]
linux = "~/.cargo"

[fish]
path = "fish"
[fish.target]
linux = "~/.config/fish"

[ghostty]
path = "ghostty"
[ghostty.target]
linux = "~/.config/ghostty"

[git]
path = "git"
[git.target]
linux = "~/.config/git"
windows = "~/.config/git"

[go]
path = "go"
[go.target]
linux = "~/.config/go"
windows = "~/AppData/Roaming/go"

[lazygit]
path = "lazygit"
[lazygit.target]
linux = "~/.config/lazygit"
windows = "~/AppData/Local/lazygit"

[mpv]
path = "mpv"
[mpv.target]
linux = "~/.config/mpv"
windows = "~/AppData/Roaming/mpv"

[niri]
path = "niri"
[niri.target]
linux = "~/.config/niri"

[npm]
path = "npm/npmrc"
[npm.target]
linux = "~/.npmrc"

[nvim]
path = "nvim"
[nvim.target]
linux = "~/.config/nvim"
windows = "~/AppData/Local/nvim"

[pip]
path = "pip"
[pip.target]
linux = "~/.config/pip"

[pwsh]
path = "pwsh/Microsoft.PowerShell_profile.ps1"
[pwsh.target]
windows = "~/Documents/PowerShell/Microsoft.PowerShell_profile.ps1"

[sqlite3]
path = "sqlite3"
[sqlite3.target]
linux = "~/.config/sqlite3"

[zellij]
path = "zellij"
[zellij.target]
linux = "~/.config/zellij"
windows = "~/AppData/Roaming/zellij"
