[dotfiles.alacritty]
exec = "alacritty"
target = "~/.config/alacritty"
target_windows = "${APPDATA}/alacritty"

[dotfiles.bash]
exec = "bash"
source = "bash/bashrc"
target = "~/.bashrc"

[dotfiles.git]
exec = "git"
target = "~/.config/git"

[dotfiles.go]
exec = "go"
source = "go/env"
target = "~/.config/go/env"
target_windows = "${APPDATA}/go/env"

[dotfiles.ghostty]
exec = "ghostty"
target = "~/.config/ghostty"

[dotfiles.lazygit]
exec = "lazygit"
source = "lazygit/config.yml"
target = "~/.config/lazygit/config.yml"
target_windows = "${LOCALAPPDATA}/lazygit/config.yml"

[dotfiles.mpv]
exec = "mpv"
target = "~/.config/mpv"
target_windows = "${APPDATA}/mpv"

[dotfiles.nvim]
exec = "nvim"
target = "~/.config/nvim"
target_windows = "${LOCALAPPDATA}/nvim"

[dotfiles.tmux]
exec = "tmux"
target = "~/.config/tmux"

[dotfiles.yazi]
exec = "yazi"
target = "~/.config/yazi"
target_windows = "${APPDATA}/yazi/config"
