[alacritty]
exec = "alacritty"

[bash]
exec = "bash"

[dunst]
exec = "dunst"

[go]
exec = "go"

[mpv]
exec = "mpv"

[picom]
exec = "picom"

[tmux]
exec = "tmux"

[bin]
target_type = "home"

[git]
relative_path = "git/gitconfig"
target_type = "home"
exec = "git"

[sqlite3]
relative_path = "sqlite3/sqliterc"
target_type = "home"
exec = "sqlite3"
