format = """
$directory\
$git_branch\
$git_status\
$docker_context\
$buf\
$dart\
$elixir\
$elm\
$golang\
$lua\
$nodejs\
$python
[» ](#bd93f9)
"""

# # Disable the blank line at the start of the prompt
# add_newline = false

[directory]
style = "bg:#2e9599"
format = "[](fg:#2e9599)[ $path ]($style)[](fg:#2e9599)"
truncation_length = 3
# truncation_symbol = "…/"

[docker_context]
symbol = " "
style = "bg:#6272a4"
format = '[ $symbol $context ]($style) $path'

[git_branch]
symbol = ""
style = "bg:#6272a4"
format = ' [](fg:#6272a4)[ $symbol $branch]($style)'

[git_status]
style = "bg:#6272a4"
format = '[ $all_status$ahead_behind ]($style)[](fg:#6272a4)'

[buf]
symbol = " "
style = "bg:#689ef0"
format = " [](fg:#689ef0)[via $symbol]($style)[](fg:#689ef0)"

[dart]
symbol = " "
style = "bg:#689ef0"
format = " [](fg:#689ef0)[via $symbol]($style)[](fg:#689ef0)"

[elixir]
symbol = " "
style = "bg:#689ef0"
format = " [](fg:#689ef0)[via $symbol]($style)[](fg:#689ef0)"

[elm]
symbol = " "
style = "bg:#689ef0"
format = " [](fg:#689ef0)[via $symbol]($style)[](fg:#689ef0)"

[golang]
symbol = " "
style = "bg:#689ef0"
format = ' [](fg:#689ef0)[via $symbol]($style)[](fg:#689ef0)'

[lua]
symbol = " "
style = "bg:#689ef0"
format = " [](fg:#689ef0)[via $symbol]($style)[](fg:#689ef0)"

[nodejs]
symbol = " "
style = "bg:#689ef0"
format = " [](fg:#689ef0)[via $symbol]($style)[](fg:#689ef0)"

[python]
symbol = " "
style = "bg:#689ef0"
format = " [](fg:#689ef0)[via $symbol]($style)[](fg:#689ef0)"
