format = """
$directory\
$git_branch\
$git_status\
$docker_context
[» ](#bd93f9)
"""

# # Disable the blank line at the start of the prompt
# add_newline = false

[directory]
style = "bg:#2e9599"
format = "[](fg:#2e9599)[ $path ]($style)[](fg:#2e9599)"
truncation_length = 3
# truncation_symbol = "…/"

[docker_context]
symbol = " "
style = "bg:#6272a4"
format = '[ $symbol $context ]($style) $path'

[git_branch]
symbol = ""
style = "bg:#6272a4"
format = ' [](fg:#6272a4)[ $symbol $branch]($style)'

[git_status]
style = "bg:#6272a4"
format = '[ $all_status$ahead_behind ]($style)[](fg:#6272a4)'
