title='${filename} - mpv'    # MPV 窗口标题
save-position-on-quit=yes    # 在退出时记住播放位置
keep-open=yes                # 视频播放完毕后不关闭窗口
osd-font-size=30             # 设置界面字体大小
volume=0                     # 默认音量为 0
loop-playlist=inf            # 按播放列表循环
osd-playlist-entry=filename  # 界面显示文件名而不是视频标题
